### PR TITLE
Add mc scripts list subcommand

### PR DESCRIPTION
**Pull request by EslamElHusseiny**

### CODE REVIEW

**Comment by eyalbe4** [comment]
@EslamElHusseiny,
Thanks you for this contribution!

Will you be able to add integration tests for the new command? You can look at the integration tests for Artifactory as a reference (see *artifactory_test.go*).
We currently don't have integration tests for Mission Control, but we were planning to add them before we extend the Mission Control support by JFrog CLI.

Also, can you please join our contributors community by signing [JFrog's CLA](https://secure.echosign.com/public/hostedForm?formid=5IYKLZ2RXB543N) so that we can merge your code?

**Comment by EslamElHusseiny** [comment]
@eyalbe4 

I'll have a look at the integrations tests and add them.

I already joined the contributors' community and signed the JFrog's CLA a few days ago.

**Comment by eyalbe4** [comment]
@EslamElHusseiny,
Since scripts are no longer supported in the latest release of Mission Control, I'm not sure we should support it in JFrog CLI.

**Comment by EslamElHusseiny** [comment]
Is it really not supported? I still can see `Execute Script` in MC v3.5.5!

**Pull request closed without merging**
