### PR TITLE
feat: support go1.22 build

### PR DESCRIPTION
**Pull request by chenrui333**
- [ ] All [tests](https://github.com/jfrog/jfrog-cli/CONTRIBUTING.md#tests) have passed. If this feature is not already covered by the tests, new tests have been added.
- [ ] The pull request is targeting the `dev` branch.
- [ ] The code has been validated to compile successfully by running `go vet ./...`.
- [ ] The code has been formatted properly using `go fmt ./...`.

---

- relates to https://github.com/Homebrew/homebrew-core/pull/163578

### CODE REVIEW

**Comment by chenrui333** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by chenrui333** [comment]
recheck

**Comment by chenrui333** [comment]
cc @RobiNino @sverdlov93

**Comment by eyalbe4** [comment]
@chenrui333,
The teats failures are probably caused because the go version should also be updated in the workflows under https://github.com/jfrog/jfrog-cli/tree/dev/.github/workflows

**Comment by eyalbe4** [comment]
Also notice @chenrui333 that I have changed the target branch of this PR from v2 to dev. According to our Contribution Guidelines, PRs should be created for the dev branch.

**Comment by chenrui333** [comment]
@eyalbe4 hmm, sorry, I missed it, I was just using whatever default head branch.

**Comment by eyalbe4** [comment]
@chenrui333,
There are also additional tasks that are related to JFrog CLI's release process before JFrog CLI can be released with go 1.22. We will be handling them internally, and there's a chance this PR's merge will need wait a bit till we get this work done.

**Comment by chenrui333** [comment]
got you, make sense

Feel free to close this PR if it fits :)

**Comment by chenrui333** [comment]
@eyalbe4 I have refreshed the PR with the latest dev branch, let me know if it works for you now. Thanks! :)

**Comment by EyalDelarea** [comment]
> @eyalbe4 I have refreshed the PR with the latest dev branch, let me know if it works for you now. Thanks! :)

Hey @chenrui333,

Thank you for this PR, but unfortunately updating the go version only in the CLI is not enough.

I'm currently working on updating the CLI to Go 1.22.x.
It has to do with prerequisites which are internal to JFrog, and updating all of the CLI components go versions.
I will update you once the CLI Go version has been updated.

Thank you very much for your contribution!

**Comment by chenrui333** [comment]
> It has to do with prerequisites which are internal to JFrog, and updating all of the CLI components go versions.
> I will update you once the CLI Go version has been updated.

that makes sense, @EyalDelarea any timeline for this (so that I can remove the go1.22 build patch on the brew side)

**Comment by EyalDelarea** [comment]
> > It has to do with prerequisites which are internal to JFrog, and updating all of the CLI components go versions.
> > I will update you once the CLI Go version has been updated.
> 
> that makes sense, @EyalDelarea any timeline for this (so that I can remove the go1.22 build patch on the brew side)

Don't have an exact timeline, but hoping until next CLI release the go version will be updated as well. 
Will keep you updated here 👍

**Comment by EyalDelarea** [comment]
Hey @chenrui333 

We just released the new CLI version `v2.57.0` which uses Go `1.22.3`

I'm closing this pull request, but feel free to reach out if you have any questions.

**Pull request closed without merging**
