### PR TITLE
Changed the main.go path to ../main.go

### PR DESCRIPTION
**Pull request by YonatanHen**
- [ ] All [tests](https://github.com/jfrog/jfrog-cli#tests) passed. If this feature is not already covered by the tests, I added new tests.
- [ ] All [static analysis checks](https://github.com/jfrog/jfrog-cli/actions/workflows/analysis.yml) passed.
- [x] This pull request is on the dev branch.
- [ ] I used gofmt for formatting the code before submitting the pull request.
-----
When attempting to run the build on MacOS using the 'sh build.sh' command, the build process encountered a failure due to an incorrect path of the main.go file, with the following message:
`no required module provides package main.go; to add it:
        go get main.go`
However, after modifying the build.sh file and updating the path to ../main.go, the build process was successful.

### CODE REVIEW

**Comment by YonatanHen** [comment]
> **CLA Assistant Lite bot:** Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://jfrog.com/cla/) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.
> 
> I have read the CLA Document and I hereby sign the CLA
> 
> You can retrigger this bot by commenting **recheck** in this Pull Request

**Comment by YonatanHen** [comment]
recheck

**Comment by YonatanHen** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by YonatanHen** [comment]
recheck

**Comment by yahavi** [comment]
Hi @YonatanHen ,
In order to build the JFrog CLI, we run the following command from the root of the repository:
```sh
./build/build.sh
```

After this PR is merged, it will not work anymore.

**Pull request closed without merging**
