### PR TITLE
feature: Add the ability to list an uploaded file for download

### PR DESCRIPTION
**Pull request by djgilcrease**
https://www.jfrog.com/confluence/display/BT/Bintray+REST+API#BintrayRESTAPI-FileinDownloadList

requires: https://github.com/jfrog/jfrog-client-go/pull/51

`jfrog bt upload --user soandso --key 1234 --publish --list-download path/to/file subject/repo/package/version`

### CODE REVIEW

**Comment by djgilcrease** [comment]
Any feedback, or progress on merging this?

**Comment by djgilcrease** [comment]
This is to make it so I do not have to call a curl command after every artifact upload to bintray (eg https://gitlab.com/f5-pwe/kog/blob/master/.gitlab-ci.yml#L165)

**Comment by eyalbe4** [comment]
Thank you for this PR @djgilcrease!
It looks like the PR includes many unintended changes, as a result of spacing and indentation. Will you be able to clean it up?
Can you also set the PR to *dev* branch and not the *master*? See the *Guidelines* section in the README. 
Thanks

**Comment by djgilcrease** [comment]
I ran go fmt on the files. I will try to get time this week to rebase on dev

**Comment by djgilcrease** [comment]
ok rebased off of dev - marked as WIP until https://github.com/jfrog/jfrog-client-go/pull/51 is merged

**Comment by djgilcrease** [comment]
@eyalbe4 can you check this one out now that jfrog/jfrog-client-go#51 is merged

**Comment by djgilcrease** [comment]
ping @eyalbe4

**Comment by eyalbe4** [comment]
@djgilcrease - sorry for the late response.

I think that the following command will fail:
```
jfrog bt u build.sh eyalbr/generic/b/1.0.0 --list-download
```
To make it work, the ```--publish``` option must be added to command. Without it, Bintray will fail the listing operation only after the file is uploaded. I therefore suggest accepting the new ``` --list-download``` option only when the ```--publish``` option is also sent.

Let me know what you think.

**Comment by djgilcrease** [comment]
Done, I thought about having `--list-download` just imply `--publish` by ensuring it set `params.Publish = true` but it looks like the current practice in the rest of the code is to return an error so whats what I change it to.

**Pull request merged**
