### PR TITLE
Add --fail-fast option

### PR DESCRIPTION
**Pull request by matteosilv**
- [X] All [tests](https://github.com/jfrog/jfrog-cli#tests) passed. If this feature is not already covered by the tests, I added new tests.
- [X] This pull request is on the dev branch.
- [X] I used gofmt for formatting the code before submitting the pull request.
-----

Needs to wait new release of jfrog/jfrog-client-go for pull requests for jfrog/jfrog-client-go#341 and jfrog/jfrog-client-go#344.
and then update required version in go.mod

### CODE REVIEW

**Comment by matteosilv** [comment]
Hi, what i have to do to understand why the checks are failing?

**Review by eyalbe4 — APPROVED** [review]
Looks good!
Feel free to resolve the conflicts and we'll merge it.
Thanks!

**Comment by matteosilv** [comment]
Can you merge? do i need to verify something else?

**Comment by matteosilv** [comment]
@eyalbe4 do we need additional approval?

**Pull request merged**
